# Generated by Django 2.2.5 on 2019-11-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.DateField(),
        ),
    ]
