# Generated by Django 2.2.5 on 2019-11-02 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20191102_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='taged_users',
            field=models.ManyToManyField(blank=True, related_name='taged_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='posts.Tags'),
        ),
    ]
