# Generated by Django 2.2.5 on 2019-11-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20191102_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='about_post',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
