# Generated by Django 2.2.5 on 2019-11-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20191102_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='is_t_type',
            field=models.BooleanField(default=False),
        ),
    ]
