# Generated by Django 2.2.5 on 2019-11-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_post_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimages',
            name='image_tag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
