# Generated by Django 2.2.5 on 2019-11-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20191102_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
