# Generated by Django 2.2.5 on 2019-11-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20191104_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
