# Generated by Django 2.2.5 on 2019-11-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20191105_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='is_star_type',
            field=models.BooleanField(default=False),
        ),
    ]
