# Generated by Django 2.2.5 on 2019-11-05 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_projecttype_is_star_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='project_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_project_category', to='posts.ProjectCategory'),
        ),
    ]
