# Generated by Django 2.2.5 on 2019-12-13 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0019_reportapost'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvolvementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportReasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarkInvolvement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_for_element', models.CharField(blank=True, max_length=500)),
                ('keyword_for_material', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to='Involvement_images')),
                ('enter_link', models.TextField(blank=True)),
                ('involvement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.InvolvementType')),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_by', to=settings.AUTH_USER_MODEL)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='involvement_marked_id', to='posts.Post')),
            ],
        ),
    ]
