# Generated by Django 2.2.5 on 2019-12-16 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_involvementtype_markinvolvement_reportreasons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportapost',
            name='text',
        ),
        migrations.AddField(
            model_name='reportapost',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.ReportReasons'),
        ),
    ]
