# Generated by Django 2.2.5 on 2019-10-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
