# Generated by Django 2.2.5 on 2019-11-13 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
