# Generated by Django 2.2.5 on 2019-11-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='total_comments',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='total_likes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='total_reported',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
