# Generated by Django 2.2.5 on 2019-12-12 13:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0011_reportapost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentLike',
            new_name='QuestionCommentLike',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='QuestionComments',
        ),
        migrations.RenameModel(
            old_name='ReportAPost',
            new_name='QuestionReport',
        ),
    ]
