# Generated by Django 2.2.5 on 2019-12-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_question_total_shares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
