# Generated by Django 2.2.5 on 2020-01-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_auto_20191227_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='question',
            name='mobile_number',
        ),
    ]
