# Generated by Django 2.2.5 on 2020-02-11 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportchat',
            old_name='report_id',
            new_name='reason_id',
        ),
        migrations.AlterUniqueTogether(
            name='reportchat',
            unique_together={('chat_id', 'reason_id')},
        ),
    ]
