# Generated by Django 2.2.5 on 2020-02-20 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20200211_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockUserChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blocked_by', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='reportchat',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reportchat',
            name='reason_id',
        ),
        migrations.RemoveField(
            model_name='reportchat',
            name='reported_by',
        ),
        migrations.DeleteModel(
            name='ChatReportReasons',
        ),
        migrations.DeleteModel(
            name='ReportChat',
        ),
        migrations.AddConstraint(
            model_name='blockuserchat',
            constraint=models.UniqueConstraint(fields=('user_id', 'blocked_by'), name='unique_user_blocked_ids'),
        ),
    ]
