# Generated by Django 2.2.5 on 2020-02-25 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitations', '0003_auto_20151126_1523'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invitation_id', to='invitations.Invitation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
