# Generated by Django 2.2.5 on 2020-02-25 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_postowner_created_on'),
        ('post_invitations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationpost',
            name='user_id',
        ),
        migrations.AddField(
            model_name='invitationpost',
            name='post_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invited_post_id', to='posts.Post'),
            preserve_default=False,
        ),
    ]
