# Generated by Django 2.2.5 on 2019-10-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_guest',
            field=models.BooleanField(default=True),
        ),
    ]
