# Generated by Django 2.2.5 on 2019-10-22 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscriptionplan'),
        ('accounts', '0002_auto_20191021_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussinessarea',
            name='subscription',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='barea_subs', to='subscriptions.SubscriptionPlan'),
        ),
    ]
