# Generated by Django 2.2.5 on 2019-11-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191106_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
