# Generated by Django 2.2.5 on 2019-11-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191108_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_subscription_plan_active',
            field=models.BooleanField(default=True),
        ),
    ]
