# Generated by Django 2.2.5 on 2019-11-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_company_is_subscription_plan_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_subscription_plan_active',
            field=models.BooleanField(default=False),
        ),
    ]
