# Generated by Django 2.2.5 on 2019-11-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191127_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('1', 'Personal'), ('2', 'Company'), ('3', 'Company_colleague')], max_length=20),
        ),
    ]
