# Generated by Django 2.2.5 on 2019-11-28 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20191128_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='colleague_company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colleague_company', to='accounts.Company'),
        ),
    ]
