# Generated by Django 2.2.5 on 2019-11-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_colleague_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='no_of_colleague_create',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
