# Generated by Django 2.2.5 on 2019-11-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_company_no_of_colleague_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='colleague_pass',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
