# Generated by Django 2.2.5 on 2019-11-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_colleague_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_more_than_5_account',
            field=models.BooleanField(default=False),
        ),
    ]
