# Generated by Django 2.2.5 on 2019-12-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_company_is_more_than_5_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('1', 'Personal'), ('2', 'Company'), ('3', 'Company_colleague'), ('4', 'Guest')], max_length=20),
        ),
    ]
