# Generated by Django 2.2.5 on 2019-12-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20191205_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='lat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='lon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
