# Generated by Django 2.2.5 on 2020-01-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200102_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('1', 'Personal'), ('2', 'Company'), ('3', 'Company colleague'), ('4', 'Guest')], max_length=20),
        ),
    ]
