# Generated by Django 2.2.5 on 2020-02-05 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_profilereportreasons_reportprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileFlagReasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FlagProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('flaged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flaged_by', to=settings.AUTH_USER_MODEL)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flaged_reason', to='accounts.ProfileFlagReasons')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flaged_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
