# Generated by Django 2.2.5 on 2020-02-06 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_flagprofile_profileflagreasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagprofile',
            name='flaged_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flaged_profile_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flagprofile',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flaged_profile_reason', to='accounts.ProfileFlagReasons'),
        ),
        migrations.AlterUniqueTogether(
            name='flagprofile',
            unique_together={('user', 'flaged_by')},
        ),
    ]
