# Generated by Django 2.2.5 on 2020-03-16 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20200214_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogInData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_in', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField()),
                ('last_logout', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_log_in', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
