# Generated by Django 2.2.5 on 2020-03-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_logindata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindata',
            name='last_login',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='logindata',
            name='last_logout',
            field=models.DateTimeField(blank=True),
        ),
    ]
