# Generated by Django 2.2.5 on 2020-03-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20200316_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindata',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logindata',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
