# Generated by Django 2.2.5 on 2020-02-20 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='content',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='title',
            new_name='question',
        ),
        migrations.AlterUniqueTogether(
            name='faq',
            unique_together={('question',)},
        ),
        migrations.AlterUniqueTogether(
            name='privacypolicy',
            unique_together={('title',)},
        ),
        migrations.AlterUniqueTogether(
            name='termsandcondition',
            unique_together={('title',)},
        ),
        migrations.CreateModel(
            name='AboutUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('1', 'AboutUs'), ('2', 'fbLink'), ('3', 'twitterLink'), ('4', 'instaLink')], max_length=1)),
                ('content', models.CharField(max_length=512)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'unique_together': {('key',)},
            },
        ),
    ]
