# Generated by Django 2.2.5 on 2019-09-30 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelrDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ivp_method', models.CharField(blank=True, max_length=10)),
                ('ivp_store', models.PositiveIntegerField()),
                ('ivp_authkey', models.CharField(blank=True, max_length=50)),
                ('ivp_cart', models.CharField(blank=True, max_length=20)),
                ('ivp_test', models.PositiveIntegerField()),
                ('ivp_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('ivp_currency', models.CharField(blank=True, max_length=5)),
                ('ivp_desc', models.CharField(blank=True, max_length=100)),
                ('return_auth', models.CharField(blank=True, max_length=300)),
                ('return_can', models.CharField(blank=True, max_length=300)),
                ('return_decl', models.CharField(blank=True, max_length=300)),
                ('ivp_trantype', models.CharField(blank=True, max_length=10)),
                ('bill_custref', models.PositiveIntegerField()),
                ('status', models.CharField(blank=True, default='get api got hit', max_length=20)),
                ('telr_ref', models.CharField(blank=True, max_length=300)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='usersubscription',
            old_name='ruser',
            new_name='user',
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_purchase', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Completed', '1'), ('Declined', '2'), ('Cancelled', '3'), ('Pending', '4')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('payment_mode', models.CharField(choices=[('Credit Card', '1'), ('Debit Card', '2'), ('Netbanking', '3'), ('Paypal', '4'), ('Terl', '5')], max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('subscription_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='splan_pay', to='subscriptions.SubscriptionPlan')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sp_pay', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
