# Generated by Django 2.2.5 on 2019-10-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20190930_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscriptionplankeyfeatures',
            name='spkf_plan',
        ),
        migrations.DeleteModel(
            name='TelrDetail',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='PaymentDetail',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlanKeyFeatures',
        ),
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
