# Generated by Django 2.2.5 on 2019-10-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0003_auto_20191022_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('plan_desc', models.CharField(max_length=800)),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('users_or_account', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('comment_on_existing_posts', models.BooleanField(default=True)),
                ('create_posts', models.BooleanField(default=False)),
                ('mark_involvement_in_others_posts', models.BooleanField(default=False)),
                ('add_pictures_link_to_others_posts', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
