# Generated by Django 2.2.5 on 2020-03-05 14:02

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('1', 'POST_INVOLVEMENT'), ('2', 'POST_COMMENT'), ('3', 'POST_LIKE'), ('4', 'POST_NEW'), ('5', 'QUESTION_NEW'), ('6', 'UPDATE_FOLLOWED_USER'), ('7', 'Chat')], max_length=1)),
                ('notification_context', django.contrib.postgres.fields.jsonb.JSONField()),
                ('notification_sender_model_name', models.CharField(max_length=50)),
                ('notification_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_by_user', to=settings.AUTH_USER_MODEL)),
                ('notification_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_for_users', to=settings.AUTH_USER_MODEL)),
            ],
        )
    ]
