# Generated by Django 2.2.5 on 2020-03-06 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20200305_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        )
    ]
