# Generated by Django 2.2.5 on 2020-03-17 11:08

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0003_auto_20200306_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('1', 'REPORT_PROFILE'), ('2', 'REPORT_POST'), ('3', 'FLAG_PROFILE'), ('4', 'FLAG_POST'), ('5', 'NEW_REGISTRATION')], max_length=1)),
                ('notification_context', django.contrib.postgres.fields.jsonb.JSONField()),
                ('sender_model_name', models.CharField(max_length=50)),
                ('sender_pk', models.IntegerField()),
                ('read', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('notification_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_admin_user', to=settings.AUTH_USER_MODEL)),
            ],
        )
    ]
